// Code generated by goctl. DO NOT EDIT.
package types

type Category struct {
	Name string `json:"name"`
}

type CategoryCreateRequest struct {
	Name string `json:"name"`
}

type CategoryCreateResponse struct {
}

type CategoryDeleteRequest struct {
	ID int `json:"id"`
}

type CategoryDeleteResponse struct {
}

type CategoryListRequest struct {
}

type CategoryListResponse struct {
	List []Category `json:"categories"`
}

type CategoryUpdateRequest struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type CategoryUpdateResponse struct {
}

type Product struct {
	Name  string  `json:"name"`
	Price float64 `json:"price"`
}

type ProductListRequest struct {
}

type ProductListResponse struct {
	List []Product `json:"products"`
}
