// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	category "mummy-storage/cmd/api/internal/handler/category"
	product "mummy-storage/cmd/api/internal/handler/product"
	"mummy-storage/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: category.CategoryCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: category.CategoryDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: category.CategoryListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: category.CategoryUpdateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/category"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: product.ProductListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/product"),
	)
}
